name = "lectiotoday"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".open-next"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "LectioTodayDB"
database_id = "REPLACE_IN_DASHBOARD"

