name = "lectiotoday"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".open-next"

[build]
command = "npm run pages:build"

[vars]
HASH_SALT = "replace-with-a-long-random-string"
# Set these in CF dashboard → Pages → Settings → Environment variables
# TURNSTILE_SECRET = "server-secret"
# NEXT_PUBLIC_TURNSTILE_SITE_KEY = "site-key"

[[d1_databases]]
binding = "DB"
database_name = "LectioTodayDB"
database_id = "REPLACE_IN_DASHBOARD"

