name = "lectiotoday"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".open-next"
compatibility_flags = ["nodejs_compat"]

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "LectioTodayDB"
database_id = "8b3bef9e-7e15-471b-8e38-be0770529045"
migrations_dir = "db/migrations"

